apiVersion: v1
kind: Service
metadata:
    name: mysql
spec:
    type: NodePort
    ports:
    - name: mysql
      port: 3306
      targetPort: 33066
      protocol: TCP
    selector:
        app: mysql
