apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  ports:
    - name: mysql
      port: 3306
      nodePort: 33306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            nodeSelector:
                master: "true"
            containers:
            - name: mysql
              image: mysql
              imagePullPolicy: IfNotPresent
              ports:
                - contaninerPort: 3306
              - name: MYSQL_ROOT_PASSWORD
                value: "letmein"
