apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            nodeSelector:
                work: "true"
            containers:
            - name: mysql
              image: mysql
              imagePullPolicy: IfNotPresent
              ports:
                - contaninerPort: 3306
              - name: MYSQL_ROOT_PASSWORD
                value: "letmein"
