apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
spec:
    replicas: 2
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            nodeSelector:
                work: "true"
            containers:
            - name: nginx
              image: nginx
              imagePullPolicy: IfNotPresent
              volumeMounts:
              - name: api-code
                mountPath: /data/www/api
              - name: xyk-code
                mountPath: /data/www/xiaoyinka
              - name: config
                mountPath: /etc/nginx/conf.d/
            volumes:
            - name: api-code
              nfs:
                path: /api
                server: 172.16.0.17
            - name: xyk-code
              nfs:
                path: /xiaoyinka
                server: 172.16.0.17
            - name: config
              configMap:
                name: nginx
